#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="project man")]
public partial class DataClassesIncidentDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertIncident(Incident instance);
  partial void UpdateIncident(Incident instance);
  partial void DeleteIncident(Incident instance);
  #endregion
	
	public DataClassesIncidentDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["project manConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesIncidentDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesIncidentDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesIncidentDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesIncidentDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Incident> Incidents
	{
		get
		{
			return this.GetTable<Incident>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Incident")]
public partial class Incident : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _Titel_Inc;
	
	private string _Description;
	
	private string _Requester;
	
	private System.Nullable<System.DateTime> _Incident_On;
	
	private string _Level;
	
	private System.Nullable<System.DateTime> _Start_Date;
	
	private System.Nullable<System.DateTime> _Due_Date;
	
	private System.Nullable<int> _Estimated_Hour;
	
	private string _Project;
	
	private string _Inc_complited;
	
	private int _Engineer_Ids;
	
	private string _Assigned_To;
	
	private string _Testing_Team;
	
	private string _New_Action;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTitel_IncChanging(string value);
    partial void OnTitel_IncChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnRequesterChanging(string value);
    partial void OnRequesterChanged();
    partial void OnIncident_OnChanging(System.Nullable<System.DateTime> value);
    partial void OnIncident_OnChanged();
    partial void OnLevelChanging(string value);
    partial void OnLevelChanged();
    partial void OnStart_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnStart_DateChanged();
    partial void OnDue_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnDue_DateChanged();
    partial void OnEstimated_HourChanging(System.Nullable<int> value);
    partial void OnEstimated_HourChanged();
    partial void OnProjectChanging(string value);
    partial void OnProjectChanged();
    partial void OnInc_complitedChanging(string value);
    partial void OnInc_complitedChanged();
    partial void OnEngineer_IdsChanging(int value);
    partial void OnEngineer_IdsChanged();
    partial void OnAssigned_ToChanging(string value);
    partial void OnAssigned_ToChanged();
    partial void OnTesting_TeamChanging(string value);
    partial void OnTesting_TeamChanged();
    partial void OnNew_ActionChanging(string value);
    partial void OnNew_ActionChanged();
    #endregion
	
	public Incident()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Titel_Inc", DbType="VarChar(50)")]
	public string Titel_Inc
	{
		get
		{
			return this._Titel_Inc;
		}
		set
		{
			if ((this._Titel_Inc != value))
			{
				this.OnTitel_IncChanging(value);
				this.SendPropertyChanging();
				this._Titel_Inc = value;
				this.SendPropertyChanged("Titel_Inc");
				this.OnTitel_IncChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(50)")]
	public string Description
	{
		get
		{
			return this._Description;
		}
		set
		{
			if ((this._Description != value))
			{
				this.OnDescriptionChanging(value);
				this.SendPropertyChanging();
				this._Description = value;
				this.SendPropertyChanged("Description");
				this.OnDescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Requester", DbType="VarChar(50)")]
	public string Requester
	{
		get
		{
			return this._Requester;
		}
		set
		{
			if ((this._Requester != value))
			{
				this.OnRequesterChanging(value);
				this.SendPropertyChanging();
				this._Requester = value;
				this.SendPropertyChanged("Requester");
				this.OnRequesterChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Incident_On", DbType="Date")]
	public System.Nullable<System.DateTime> Incident_On
	{
		get
		{
			return this._Incident_On;
		}
		set
		{
			if ((this._Incident_On != value))
			{
				this.OnIncident_OnChanging(value);
				this.SendPropertyChanging();
				this._Incident_On = value;
				this.SendPropertyChanged("Incident_On");
				this.OnIncident_OnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Level]", Storage="_Level", DbType="VarChar(50)")]
	public string Level
	{
		get
		{
			return this._Level;
		}
		set
		{
			if ((this._Level != value))
			{
				this.OnLevelChanging(value);
				this.SendPropertyChanging();
				this._Level = value;
				this.SendPropertyChanged("Level");
				this.OnLevelChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Start_Date", DbType="Date")]
	public System.Nullable<System.DateTime> Start_Date
	{
		get
		{
			return this._Start_Date;
		}
		set
		{
			if ((this._Start_Date != value))
			{
				this.OnStart_DateChanging(value);
				this.SendPropertyChanging();
				this._Start_Date = value;
				this.SendPropertyChanged("Start_Date");
				this.OnStart_DateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Due_Date", DbType="Date")]
	public System.Nullable<System.DateTime> Due_Date
	{
		get
		{
			return this._Due_Date;
		}
		set
		{
			if ((this._Due_Date != value))
			{
				this.OnDue_DateChanging(value);
				this.SendPropertyChanging();
				this._Due_Date = value;
				this.SendPropertyChanged("Due_Date");
				this.OnDue_DateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estimated_Hour", DbType="Int")]
	public System.Nullable<int> Estimated_Hour
	{
		get
		{
			return this._Estimated_Hour;
		}
		set
		{
			if ((this._Estimated_Hour != value))
			{
				this.OnEstimated_HourChanging(value);
				this.SendPropertyChanging();
				this._Estimated_Hour = value;
				this.SendPropertyChanged("Estimated_Hour");
				this.OnEstimated_HourChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Project", DbType="VarChar(50)")]
	public string Project
	{
		get
		{
			return this._Project;
		}
		set
		{
			if ((this._Project != value))
			{
				this.OnProjectChanging(value);
				this.SendPropertyChanging();
				this._Project = value;
				this.SendPropertyChanged("Project");
				this.OnProjectChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Inc_complited", DbType="VarChar(50)")]
	public string Inc_complited
	{
		get
		{
			return this._Inc_complited;
		}
		set
		{
			if ((this._Inc_complited != value))
			{
				this.OnInc_complitedChanging(value);
				this.SendPropertyChanging();
				this._Inc_complited = value;
				this.SendPropertyChanged("Inc_complited");
				this.OnInc_complitedChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Engineer_Ids", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int Engineer_Ids
	{
		get
		{
			return this._Engineer_Ids;
		}
		set
		{
			if ((this._Engineer_Ids != value))
			{
				this.OnEngineer_IdsChanging(value);
				this.SendPropertyChanging();
				this._Engineer_Ids = value;
				this.SendPropertyChanged("Engineer_Ids");
				this.OnEngineer_IdsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Assigned_To", DbType="VarChar(50)")]
	public string Assigned_To
	{
		get
		{
			return this._Assigned_To;
		}
		set
		{
			if ((this._Assigned_To != value))
			{
				this.OnAssigned_ToChanging(value);
				this.SendPropertyChanging();
				this._Assigned_To = value;
				this.SendPropertyChanged("Assigned_To");
				this.OnAssigned_ToChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Testing_Team", DbType="VarChar(50)")]
	public string Testing_Team
	{
		get
		{
			return this._Testing_Team;
		}
		set
		{
			if ((this._Testing_Team != value))
			{
				this.OnTesting_TeamChanging(value);
				this.SendPropertyChanging();
				this._Testing_Team = value;
				this.SendPropertyChanged("Testing_Team");
				this.OnTesting_TeamChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[New Action]", Storage="_New_Action", DbType="VarChar(50)")]
	public string New_Action
	{
		get
		{
			return this._New_Action;
		}
		set
		{
			if ((this._New_Action != value))
			{
				this.OnNew_ActionChanging(value);
				this.SendPropertyChanging();
				this._New_Action = value;
				this.SendPropertyChanged("New_Action");
				this.OnNew_ActionChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
